Hard homework1
made-ml-in-prod-2022/andrey-source pull request #2
Opened 2022-05-15 11:22 UTC by andrey-source

https://github.com/made-ml-in-prod-2022/andrey-source/pull/1

Добавил кастомный трансформер в виде column transformer. Который сжимает onehotencoder, логистической регрессией с  l1 регуляризацией. Добавил тесты. Добавил ci (дохленький). Ну и минорные фиксы по проекту

2022-05-22 19:58 UTC, nickdndev requested changes
отлично , есть пару вопров:
1. неодходимо добавить в гит игнор питон кеш , в мастер это не должно идти 
2. если доработки были после софт дедлайна, то отпишитесь пожалуйста в комментах , что было сделано после софта , но PR должен быть один на master ветку , а не на home1 ветку

2022-05-22 19:58 UTC, nickdndev commented on src/models/custom_transformer.py
> +            raise Exception('CustomColumnTransformer')
make user friendly message , like "Transformer is not fitted "

2022-05-22 19:58 UTC, nickdndev commented on tests/tests.py
> +        self.assertDictEqual({'accuracy': 0.906, 'recall': 0.898, 'precision': 0.898}, metrics)
need to check delta +- 5-10%

2022-05-22 19:58 UTC, nickdndev commented on src/predict.py
> +    logger.info("The forecast by address {}".format(params.data_test_path))
use f"The forecast by address {params.data_test_path}"

2022-05-26 19:48 UTC, andrey-source commented on src/models/custom_transformer.py
> +            raise Exception('CustomColumnTransformer')
К вопросу про одну ветку. У нас на портале написано: "Первое домашнее задание можно разделить на 2 порции в случае если вы не успеваете доделать ту или иную функциональность до софт дедлайна.
Привила следующие:
1) До дедлайна оформляете пул реквест со сделанной функциональностью 
2) Создаете от ветки homework1 ветку homework1_hard
3) Создаете пулл реквест из ветки homework1_hard в homework, в описании указываете ссылку на первый реквест и описываете что было доделано (добавляете того ревьювера, который проверял первый реквест(если уже ее уже начали проверять))"

Я вроде так и постарался сделать, соответственно в описании к этому пул реквесту то что я добавил после soft дедлайна

2022-05-28 21:08 UTC, nickdndev commented on src/models/custom_transformer.py
> +            raise Exception('CustomColumnTransformer')
ок

2022-05-28 21:10 UTC, nickdndev requested changes
Оставьте пожалуйста оценку за hard homework

2022-05-29 19:32 UTC, andrey-source commented
Добавил самооценку в ридми

2022-05-30 18:02 UTC, merged